### ISSUE TITLE
Local database

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#12]
## Libraries used
- Android Room Library
## Tasks
- [x] Add new muffle point.
- [x] Update existent muffle point.
- [x] Delete existent muffle point.
