### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#28]
## Tasks
- [x] Add firebase analytics integration
- [x] Add firebase performance integration
- [x] Add firebase crashlytics integration
- [x] Add remote configs for the location waiting values
