### ISSUE TITLE
SelectMufflePositionActivity UI

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#3]
## UI Preview
![SelectMufflePointActivity](https://user-images.githubusercontent.com/5838137/69956886-92302200-1501-11ea-8efd-b82be2a915a9.png)
## Tasks
- [x] Maps to select the muffle point.
- [x] Search single-line textfield to search for a position.
- [x] Floating action button to focus the current location on the map.
- [x] Ok button on the action bar to submit the selected position.
- [x] Open this activity from the #2 AddMufflePointActivity with a tap on the maps preview.
