### ISSUE TITLE
Alpha release 0.1.0

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#36]
## Task
- [x] Add release google maps key
- [x] Code and resource clean up
- [x] Build release apk
