### ISSUE TITLE
EditMufflePointActivity UI

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#4]
## UI Preview
![EditMufflePointActivity](https://user-images.githubusercontent.com/5838137/69957118-374afa80-1502-11ea-90ea-14bb0a5f8db0.png)
## Tasks
- [x] Maps preview of the muffle point.
- [x] Switch to enable/disable the muffle point.
- [x] Single-line textfield with floating label for the muffle point name.
- [x] Slider for the range. Range from 100m to 2000m.
- [x] Group of slider for each audio stream supported on android phone.
- [x] Add checkbox to each audio stream slider for enable/disable volume changes on this audio stream.
- [x] Add save button to the action bar for saving the new muffle point.
- [x] Delete button on the bottom of the slider group.
- [x] Open this activity from the #1 MainActivity with the edit button on the card.
