### ISSUE TITLE
Move range slider UI

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#56]
## Tasks
- [ ] Move the range slider from the Add-/EditMufflePointActivity to the SelectMufflePointActivity.
- [ ] Update the EditMufflePointActivity to open the SelectMufflePointActivity.
- [ ] Update the SelectMufflePointActivity to only allow position changes and show current position only from the AddMufflePointActivity.
- [ ] Update the zoom level for the range selection.
