### ISSUE TITLE
Muffle Point time property

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#57]
## Description
Muffle points should have a optional time property to only activate in a given time periode.
## Tasks
- [ ] Update muffle point entity.
- [ ] Add expendable time category to the Add- and EditMufflePointActivity.
  - Slider to enable and disable the time property.
  - Two fields for time periode beginn and end.
- [ ] Update search for check if muffle point is in range.
