### ISSUE TITLE
In muffle area check

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#6]
## Tasks
- [x] Run on GPS location updates.
- [x] Check if the user entered or left a muffle area.
- [x] Notify audio manager to update audio volumes.
