### ISSUE TITLE
AudioManager

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#7]
## Tasks
- [x] Get audio volumes from the database for a muffle area id.
- [x] Update the audio streams according to the database values.
- [x] Track active muffle points.
