### ISSUE TITLE
MainActivity Backend

### ISSUE THREAD

**Issue by korti11** [korti11/muffle#8]
## Tasks
- [x] Lazy load the neede values from the database to show the cards for each muffle point.
- [x] Load the first 3 to 4 muffle points and then load 1 muffle point every time a new card needs to be shown.
- [x] Enable/Disable muffle point in the database if the button for this action is pressed.
